<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;
class DistrictsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('cities')->delete();

        $districts = [
            [
                'id' => 1,
                'name' => 'Darjiling',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.98675690',
                'longitude' => '87.85497550',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1356',
            ],
            [
                'id' => 2,
                'name' => 'Jalpaiguri',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.98675690',
                'longitude' => '87.85497550',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1357',
            ],
            [
                'id' => 3,
                'name' => 'Koch Bihar',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.98675690',
                'longitude' => '87.85497550',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1358',
            ],
            [
                'id' => 4,
                'name' => 'Uttar Dinajpur',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.98675690',
                'longitude' => '87.85497550',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1359',
            ],
            [
                'id' => 5,
                'name' => 'Dakshin Dinajpur',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.98675690',
                'longitude' => '87.85497550',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1360',
            ],
            [
                'id' => 6,
                'name' => 'Maldah',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '25.01680000',
                'longitude' => '88.60685000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1361',
            ],
            [
                'id' => 7,
                'name' => 'Murshidabad',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '24.19090000',
                'longitude' => '88.27800000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1362',
            ],
            [
                'id' => 8,
                'name' => 'Birbhum',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '23.76660000',
                'longitude' => '87.38020000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1363',
            ],
            [
                'id' => 9,
                'name' => 'Barddhaman',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '23.02580000',
                'longitude' => '87.86440000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1364',
            ],
            [
                'id' => 10,
                'name' => 'Nadia',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '23.30460000',
                'longitude' => '88.53040000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1365',
            ],
            [
                'id' => 11,
                'name' => 'North Twenty Four Parganas',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.65180000',
                'longitude' => '88.45360000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1366',
            ],
            [
                'id' => 12,
                'name' => 'Hoogly',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.79290000',
                'longitude' => '88.38400000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1367',
            ],
            [
                'id' => 13,
                'name' => 'Bankura',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '23.23540000',
                'longitude' => '87.07390000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1368',
            ],
            [
                'id' => 14,
                'name' => 'Puruliya',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '23.38330000',
                'longitude' => '86.34860000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1369',
            ],
            [
                'id' => 15,
                'name' => 'Medinipur',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.92980000',
                'longitude' => '87.89470000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1370',
            ],
            [
                'id' => 16,
                'name' => 'Howrah',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.59330000',
                'longitude' => '88.26390000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1371',
            ],
            [
                'id' => 17,
                'name' => 'Kolkata',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.57260000',
                'longitude' => '88.36390000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1372',
            ],
            [
                'id' => 18,
                'name' => 'South Twenty Four Parganas',
                'state_id' => 4853,
                'state_code' => 'WB',
                'country_id' => 101,
                'country_code' => 'IN',
                'latitude' => '22.20660000',
                'longitude' => '88.77090000',
                'created_at' => now(),
                'updated_at' => now(),
                'flag' => 1,
                'wikiDataId' => 'Q1373',
            ],
            
            // Add more districts as needed
        ];

        // Insert into the database
        \DB::table('districts')->insert($districts);
        
    }
}
